import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/app.scss";

import { ColorSchemeScript } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Techdiary",
  description: "Generated by create next app",
  openGraph: {
    title: "Techdiary",
    images: [
      {
        url: "/api/og",
        width: 1200,
        height: 630,
        alt: "Techdiary",
      },
    ],
  },
};

import AppProvider from "@/providers/AppProvider";
import React, { PropsWithChildren } from "react";

const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
};

export default RootLayout;
